name: build

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-binary:
    name: build binary
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: aarch64-unknown-linux-gnu
      - name: run build script
        run: bash build.sh
